In [1]:
import numpy as np

In [2]:
array1=np.array([1,2,3])

In [3]:
array2=np.array([[1,2,3],[2,3,4]])

In [4]:
array1

array([1, 2, 3])

In [5]:
array2

array([[1, 2, 3],
       [2, 3, 4]])

In [6]:
list1=[1,2,3]
print("list1:", list1)
print("list1 type:",type(list1))

list1: [1, 2, 3]
list1 type: <class 'list'>


In [7]:
array1=np.array(list1)
print("array1:",array1)
print("array1 type:",type(array1))

array1: [1 2 3]
array1 type: <class 'numpy.ndarray'>


In [8]:
array1=np.array([1,2,3])
print("array1 type:",type(array1))
print("array1 array 형태:", array1.shape)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)


In [10]:
array2=np.array([[1,2,3],
               [2,3,4]])
print("array2 type:",type(array2))
print("array2 array 형태:",array2.shape)

array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)


In [11]:
array3=np.array([[1,2,3]])
print("array3 type:",type(array3))
print("array3 array 헝태:",array3.shape)

array3 type: <class 'numpy.ndarray'>
array3 array 헝태: (1, 3)


In [14]:
print("array1:{:0}차원, array2:{:1}차원, array3:{:2}차원".format(array1.ndim, array2.ndim, array3.ndim))

array1:1차원, array2:2차원, array3: 2차원


In [15]:
list1=[1,2,3]
print(type(list1))
array1=np.array(list1)

print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


In [16]:
list2=[1,2,'test']
array2=np.array(list2)
print(array2, array2.dtype)

['1' '2' 'test'] <U11


In [18]:
list3=[1,2,3.0]
array3=np.array(list3)
print(array3, array3.dtype)

[1. 2. 3.] float64


In [19]:
array_int=np.array([1,2,3])
array_float=array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1=array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1=np.array([1.1,2.1,3.1])
array_int2=array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


In [22]:
array2=np.array([[1,2,3],
               [2,3,4]])
print(array2.sum())
print(array2.sum(axis=0)) #axis=0:행 간 더하기
print(array2.sum(axis=1)) #axis=1:행 안에서 더하기

15
[3 5 7]
[6 9]


In [25]:
sequence_array=np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [29]:
zero_array=np.zeros((3,2),dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array=np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


In [30]:
array1=np.arange(10)
print('array1:\n',array1)

array2=array1.reshape(2,5)
print('array2:\n', array2)

array3=array1.reshape(5,2)
print('array3:\n', array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [31]:
array1.reshape(4,3)

ValueError: cannot reshape array of size 10 into shape (4,3)

In [33]:
array1=np.arange(10)
print(array1)

#컬럼 axis 크기는 5에 고정, 로우 axis크기를 이에 맞춰 자동 변환. 즉 2X5형태로 변환
array2=array1.reshape(-1,5)
print('array2 reshape:', array2.shape)
print("array2:\n", array2)

#로우 axis 크기는 5에 고정, 컬럼 axis크기를 이에 맞춰 자동 변환. 즉 5X2형태로 변환
array3=array1.reshape(5,-1)
print('array3 reshape:', array3.shape)
print("array3:\n", array3)

[0 1 2 3 4 5 6 7 8 9]
array2 reshape: (2, 5)
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3 reshape: (5, 2)
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [35]:
#reshape()는 (-1,1),(-1,)와 같은 형태로 주로 사용
#1차원 ndarray를 2차원으로 또는 2차원 ndarray를 1차원으로 변환시 사용
array1=np.arange(5)

array2d_1=array1.reshape(-1,1)
print('array2d_1 shape:',array2d_1.shape)

array1d=array1.reshape(-1,)
print("array1d shape:", array1d.shape)
print("array1d:\n", array1d)

array2d_1 shape: (5, 1)
array1d shape: (5,)
array1d:
 [0 1 2 3 4]


In [36]:
#반드시 -1 값은 1개만 입력
array1,reshape(-1,-1) #오류

NameError: name 'reshape' is not defined

In [38]:
array1=np.arange(start=1, stop=10)
print('array1:',array1)

value=array1[2]
print('value:',value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int32'>


In [39]:
print('맨뒤의값:', array1[-1], ',맨뒤에서 두번째 값:', array1[-2])

맨뒤의값: 9 ,맨뒤에서 두번째 값: 8


In [40]:
array1[0]=9
array1[8]=0
print('array1:', array1)

array1: [9 2 3 4 5 6 7 8 0]


In [42]:
array1d=np.arange(start=1, stop=10)
array2d=array1d.reshape(3,3)
print(array2d)

print('(row=0,col=0) index가리키는 값:', array2d[0,0])
print('(row=0,col=1) index가리키는 값:', array2d[0,1])
print('(row=1,col=0) index가리키는 값:', array2d[1,0])
print('(row=2,col=2) index가리키는 값:', array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0,col=0) index가리키는 값: 1
(row=0,col=1) index가리키는 값: 2
(row=1,col=0) index가리키는 값: 4
(row=2,col=2) index가리키는 값: 9


In [43]:
array1=np.arange(start=1, stop=10)
print(array1)
array3=array1[0:3]
print(array3)
print(type(array3))

[1 2 3 4 5 6 7 8 9]
[1 2 3]
<class 'numpy.ndarray'>


In [44]:
array1=np.arange(start=1, stop=10)
array4=array1[:3]
print(array4)
array5=array1[3:]
print(array5)
array6=array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [45]:
array1d=np.arange(start=1,stop=10)
array2d=array1d.reshape(3,3)
print('array2d:\n',array2d)

print('array2d[0:2, 0:2] \n',array2d[0:2,0:2])
print('array2d[1:3, 0:3] \n',array2d[1:3,0:3])
print('array2d[1:3, :] \n',array2d[1:3,:])
print('array2d[:, :] \n',array2d[:,:])
print('array2d[:2, 1:] \n',array2d[:2,1:])
print('array2d[:2, 0] \n',array2d[:2,0])



array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
array2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] 
 [[2 3]
 [5 6]]
array2d[:2, 0] 
 [1 4]


In [46]:
array1d=np.arange(start=1,stop=10)
array2d=array1d.reshape(3,3)
print(array2d)

array3=array2d[[0,1],2]
print('array2d[[0,1],2]=>', array3.tolist())

array4=array2d[[0,2],0:2]
print('array2d[[0,2],0:2]=>', array4.tolist())

array5=array2d[[0,1]]
print('array2d[[0,1]]=>', array5.tolist())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[[0,1],2]=> [3, 6]
array2d[[0,2],0:2]=> [[1, 2], [7, 8]]
array2d[[0,1]]=> [[1, 2, 3], [4, 5, 6]]


In [47]:
array1d=np.arange(start=1, stop=10)
print(array1d)

[1 2 3 4 5 6 7 8 9]


In [49]:
print(array1d)
print(array1d>5)

var1=array1d>5
print('var1:',var1)
print(type(var1))

[1 2 3 4 5 6 7 8 9]
[False False False False False  True  True  True  True]
var1: [False False False False False  True  True  True  True]
<class 'numpy.ndarray'>


In [51]:
print(array1d)
array3=array1d[array1d>5]
print('array1d > 5 불린인덱싱 결과 값:',array3)

[1 2 3 4 5 6 7 8 9]
array1d > 5 불린인덱싱 결과 값: [6 7 8 9]


In [53]:
org_array=np.array([3,1,9,5])
print('원본행렬:',org_array)

sort_array1=np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬:',sort_array1)
print('np.sort() 호출 후 원본 행렬:',org_array)

sort_array2=org_array.sort()
org_array.sort()
print('org_array.sort() 호출 후 반환된 행렬:',sort_array2)
print('org_array.sort() 호출 후 원본 행렬:', org_array)

원본행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 원본 행렬: [3 1 9 5]
org_array.sort() 호출 후 반환된 행렬: None
org_array.sort() 호출 후 원본 행렬: [1 3 5 9]


In [54]:
sort_array1_desc=np.sort(org_array)[::-1]
print('내림차순정렬:',sort_array1_desc)

내림차순정렬: [9 5 3 1]


In [55]:
array2d=np.array([[8,12],
                 [7,1]])
sort_array2d_axis0=np.sort(array2d,axis=0)
print('로우방향정렬:\n',sort_array2d_axis0)
sort_array2d_axis1=np.sort(array2d,axis=1)
print('컬럼방향정렬:\n',sort_array2d_axis1)

로우방향정렬:
 [[ 7  1]
 [ 8 12]]
컬럼방향정렬:
 [[ 8 12]
 [ 1  7]]


In [57]:
org_array=np.array([3,1,9,5])
print(np.sort(org_array))

sort_indices=np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:',sort_indices)

[1 3 5 9]
<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [59]:
org_array=np.array([3,1,9,5])
print(np.sort(org_array)[::-1])

sort_indices_desc=np.argsort(org_array)[::-1]
print(type(sort_indices_desc))
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:',sort_indices_desc)

[9 5 3 1]
<class 'numpy.ndarray'>
행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [62]:
import pandas as pd
titanic_df=pd.read_csv('titanic_train.csv')
print('단일 컬럼 데이터 추출:\n',titanic_df[  'Pclass' ].head(3))
print('\n여러 컬럼들의 데이터 추출:\n', titanic_df[ ['Survived','Pclass']].head(3))
print('[ ] 안에 숫자 index는 keyError 오류 발생:\n', titanic_df[0])

단일 컬럼 데이터 추출:
 0    3
1    1
2    3
Name: Pclass, dtype: int64

여러 컬럼들의 데이터 추출:
    Survived  Pclass
0         0       3
1         1       1
2         1       3


KeyError: 0

In [64]:
data={'Name' : ['Chulmin','Eunkyung','Jinwoong','Soobeom'],
     'Year': [2011,2016,2015,2015],
     'Gender':['Male','Female','Male','Male']}
data_df=pd.DataFrame(data, index=['one','two','three','four'])
data_df

Name  Year  Gender
one     Chulmin  2011    Male
two    Eunkyung  2016  Female
three  Jinwoong  2015    Male
four    Soobeom  2015    Male

In [65]:
data_df.head()

Name  Year  Gender
one     Chulmin  2011    Male
two    Eunkyung  2016  Female
three  Jinwoong  2015    Male
four    Soobeom  2015    Male

In [74]:
data_df.iloc[0,1]

2011

In [75]:
data_df.loc['two','Name']

'Eunkyung'

In [77]:
value_counts=titanic_df['Pclass'].value_counts()
print(value_counts)

3    491
1    216
2    184
Name: Pclass, dtype: int64


In [78]:
titanic_pclass=titanic_df['Pclass']
print(type(titanic_pclass))

<class 'pandas.core.series.Series'>


In [79]:
value_counts=titanic_df['Pclass'].value_counts()
print(value_counts)
print(type(value_counts))

3    491
1    216
2    184
Name: Pclass, dtype: int64
<class 'pandas.core.series.Series'>


In [80]:
col_name1=['col1']
list1=[1,2,3]
array1=np.array(list1)
print('array1 shape:',array1.shape )

array1 shape: (3,)


In [81]:
df_list1=pd.DataFrame(list1, columns=col_name1)
print('1차원 리스트로 만든 DataFrame:\n',df_list1)

df_array1=pd.DataFrame(array1, columns=col_name1)
print('1차원 ndarray로 만든 DataFrame:\n', df_array1)

1차원 리스트로 만든 DataFrame:
    col1
0     1
1     2
2     3
1차원 ndarray로 만든 DataFrame:
    col1
0     1
1     2
2     3


In [83]:
col_name2=['col1','col2','col3']

list2=[[1,2,3],
      [11,12,13]]
array2=np.array(list2)
print('array2 shape: ',array2.shape)

df_list2=pd.DataFrame(list2, columns=col_name2)
print('2차원 리스트로 만든 DataFrame:\n',df_list2)
df_array2=pd.DataFrame(array2, columns=col_name2)
print('2차원 ndarray로 만든 DataFrame:\n', df_array2)

array2 shape:  (2, 3)
2차원 리스트로 만든 DataFrame:
    col1  col2  col3
0     1     2     3
1    11    12    13
2차원 ndarray로 만든 DataFrame:
    col1  col2  col3
0     1     2     3
1    11    12    13


In [84]:
dict={'col1':[1,11],'col2':[2,22],'col3':[3,33]}
df_dict=pd.DataFrame(dict)
print('딕셔너리로 만든 DataFrame:\n',df_dict)

딕셔너리로 만든 DataFrame:
    col1  col2  col3
0     1     2     3
1    11    22    33


In [86]:
array3=df_dict.values
print('df_dict.values타입:',type(array3), ', df_dict.values shape:',array3.shape)
print(array3)

df_dict.values타입: <class 'numpy.ndarray'> , df_dict.values shape: (2, 3)
[[ 1  2  3]
 [11 22 33]]


In [87]:
list3=df_dict.values.tolist()
print('df_dict.values.tolist() type:', type(list3))
print(list3)

dict3=df_dict.to_dict('list')
print('\n df_dict.to_dict() type:',type(dict3))
print(dict3)

df_dict.values.tolist() type: <class 'list'>
[[1, 2, 3], [11, 22, 33]]

 df_dict.to_dict() type: <class 'dict'>
{'col1': [1, 11], 'col2': [2, 22], 'col3': [3, 33]}


In [88]:
titanic_df['Age_0']=0
titanic_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_0  
0      0         A/5 21171   7.2500   NaN        S      0  
1      0          PC 17599  71.2833   C85        C      0  
2      0  STON/O2. 3101282   7.9250   NaN        S      0

In [89]:
titanic_drop_df=titanic_df.drop('Age_0',axis=1)
titanic_drop_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [91]:
indexes=titanic_df.index
print(indexes)
print('Index객체 array값:\n',indexes.values)

RangeIndex(start=0, stop=891, step=1)
Index객체 array값:
 [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 

In [92]:
print(type(indexes.values))
print(indexes.values.shape)
print(indexes[:5].values)
print(indexes.values[:5])
print(indexes[6])

<class 'numpy.ndarray'>
(891,)
[0 1 2 3 4]
[0 1 2 3 4]
6


In [93]:
series_fair=titanic_df['Fare']
print('Fair Series max 값:',series_fair.max())
print('Fair Series sum 값:',series_fair.sum())
print('sum() Fair Series:',sum(series_fair))
print('Fair Series + 3:\n',(series_fair+3).head(3))


Fair Series max 값: 512.3292
Fair Series sum 값: 28693.9493
sum() Fair Series: 28693.949299999967
Fair Series + 3:
 0    10.2500
1    74.2833
2    10.9250
Name: Fare, dtype: float64


In [96]:
titanic_df[titanic_df['Pclass']==3].head(3)

PassengerId  Survived  Pclass                      Name     Sex   Age  \
0            1         0       3   Braund, Mr. Owen Harris    male  22.0   
2            3         1       3    Heikkinen, Miss. Laina  female  26.0   
4            5         0       3  Allen, Mr. William Henry    male  35.0   

   SibSp  Parch            Ticket   Fare Cabin Embarked  Age_0  
0      1      0         A/5 21171  7.250   NaN        S      0  
2      0      0  STON/O2. 3101282  7.925   NaN        S      0  
4      0      0            373450  8.050   NaN        S      0

In [102]:
titanic_boolean=titanic_df[titanic_df['Age']>60]
print(type(titanic_boolean))
titanic_boolean

<class 'pandas.core.frame.DataFrame'>


PassengerId  Survived  Pclass                                       Name  \
33            34         0       2                      Wheadon, Mr. Edward H   
54            55         0       1             Ostby, Mr. Engelhart Cornelius   
96            97         0       1                  Goldschmidt, Mr. George B   
116          117         0       3                       Connors, Mr. Patrick   
170          171         0       1                  Van der hoef, Mr. Wyckoff   
252          253         0       1                  Stead, Mr. William Thomas   
275          276         1       1          Andrews, Miss. Kornelia Theodosia   
280          281         0       3                           Duane, Mr. Frank   
326          327         0       3                  Nysveen, Mr. Johan Hansen   
438          439         0       1                          Fortune, Mr. Mark   
456          457         0       1                  Millet, Mr. Francis Davis   
483          484         1       3                     Turkula, Mrs. (Hedwig)   
493          494         0       1                    Artagaveytia, Mr. Ramon   
545          546         0       1               Nicholson, Mr. Arthur Ernest   
555          556         0       1                         Wright, Mr. George   
570          571         1       2                         Harris, Mr. George   
625          626         0       1                      Sutton, Mr. Frederick   
630          631         1       1       Barkworth, Mr. Algernon Henry Wilson   
672          673         0       2                Mitchell, Mr. Henry Michael   
745          746         0       1               Crosby, Capt. Edward Gifford   
829          830         1       1  Stone, Mrs. George Nelson (Martha Evelyn)   
851          852         0       3                        Svensson, Mr. Johan   

        Sex   Age  SibSp  Parch       Ticket      Fare        Cabin Embarked  \
33     male  66.0      0      0   C.A. 24579   10.5000          NaN        S   
54     male  65.0      0      1       113509   61.9792          B30        C   
96     male  71.0      0      0     PC 17754   34.6542           A5        C   
116    male  70.5      0      0       370369    7.7500          NaN        Q   
170    male  61.0      0      0       111240   33.5000          B19        S   
252    male  62.0      0      0       113514   26.5500          C87        S   
275  female  63.0      1      0        13502   77.9583           D7        S   
280    male  65.0      0      0       336439    7.7500          NaN        Q   
326    male  61.0      0      0       345364    6.2375          NaN        S   
438    male  64.0      1      4        19950  263.0000  C23 C25 C27        S   
456    male  65.0      0      0        13509   26.5500          E38        S   
483  female  63.0      0      0         4134    9.5875          NaN        S   
493    male  71.0      0      0     PC 17609   49.5042          NaN        C   
545    male  64.0      0      0          693   26.0000          NaN        S   
555    male  62.0      0      0       113807   26.5500          NaN        S   
570    male  62.0      0      0  S.W./PP 752   10.5000          NaN        S   
625    male  61.0      0      0        36963   32.3208          D50        S   
630    male  80.0      0      0        27042   30.0000          A23        S   
672    male  70.0      0      0   C.A. 24580   10.5000          NaN        S   
745    male  70.0      1      1    WE/P 5735   71.0000          B22        S   
829  female  62.0      0      0       113572   80.0000          B28      NaN   
851    male  74.0      0      0       347060    7.7750          NaN        S   

     Age_0  
33       0  
54       0  
96       0  
116      0  
170      0  
252      0  
275      0  
280      0  
326      0  
438      0  
456      0  
483      0  
493      0  
545      0  
555      0  
570      0  
625      0  
630      0  
672      0  
745      0  
829      0  
851      0

In [104]:
titanic_df.loc[titanic_df['Age']>60,['Name','Age']].head(3)

Name   Age
33           Wheadon, Mr. Edward H  66.0
54  Ostby, Mr. Engelhart Cornelius  65.0
96       Goldschmidt, Mr. George B  71.0

In [105]:
titanic_df[(titanic_df['Age']>60)&(titanic_df['Pclass']==1)&(titanic_df['Sex']=='female')]

PassengerId  Survived  Pclass                                       Name  \
275          276         1       1          Andrews, Miss. Kornelia Theodosia   
829          830         1       1  Stone, Mrs. George Nelson (Martha Evelyn)   

        Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked  Age_0  
275  female  63.0      1      0   13502  77.9583    D7        S      0  
829  female  62.0      0      0  113572  80.0000   B28      NaN      0

In [106]:
con1=titanic_df['Age']>60
con2=titanic_df['Pclass']==1
con3=titanic_df['Sex']=='female'
titanic_df[con1&con2&con3]

PassengerId  Survived  Pclass                                       Name  \
275          276         1       1          Andrews, Miss. Kornelia Theodosia   
829          830         1       1  Stone, Mrs. George Nelson (Martha Evelyn)   

        Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked  Age_0  
275  female  63.0      1      0   13502  77.9583    D7        S      0  
829  female  62.0      0      0  113572  80.0000   B28      NaN      0

In [110]:
pip install scikit-learn

Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'c:\deep\datab\scripts\python.exe -m pip install --upgrade pip' command.


In [111]:
import sklearn
print(sklearn.__version__)

0.23.2


In [113]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [115]:
import pandas as pd

iris=load_iris()
iris_data=iris.data
iris_label=iris.target
print('iris target값:',iris_label)
print('iris target명:',iris.target_names)

iris_df=pd.DataFrame(data=iris_data, columns=iris.feature_names)
iris_df['label']=iris.target
iris_df.head(3)

iris target값: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
iris target명: ['setosa' 'versicolor' 'virginica']


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   

   label  
0      0  
1      0  
2      0

In [116]:
X_train, X_test, y_train, y_test=train_test_split(iris_data, iris_label,
                                                 test_size=0.2, random_state=11)

In [118]:
df_clf=DecisionTreeClassifier(random_state=11)

#학습수행
df_clf.fit(X_train, y_train)

DecisionTreeClassifier(random_state=11)

In [121]:
#학습 완료된 DecisionTreeClassifier객체에서 테스트데이터 세트로 예측 수행
pred=df_clf.predict(X_test)

In [122]:
pred

array([2, 2, 1, 1, 2, 0, 1, 0, 0, 1, 1, 1, 1, 2, 2, 0, 2, 1, 2, 2, 1, 0,
       0, 1, 0, 0, 2, 1, 0, 1])

In [126]:
from sklearn.metrics import accuracy_score
print('예측 정확도: {0:.4f}'.format(accuracy_score(y_test,pred)))

예측 정확도: 0.9333


In [127]:
from sklearn.datasets import load_iris

iris_data=load_iris()
print(type(iris_data))

<class 'sklearn.utils.Bunch'>


In [128]:
keys=iris_data.keys()
print('붓꽃 데이터 세트의 키들:',keys)

붓꽃 데이터 세트의 키들: dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])


In [130]:
print('\n feature_names type:', type(iris_data.feature_names))
print('\n feature_names shape:', len(iris_data.feature_names))
print(iris_data.feature_names)

print('\n target_names type:', type(iris_data.target_names))
print('\n target_names shape:', len(iris_data.target_names))
print(iris_data.target_names)

print('\n data type:', type(iris_data.data))
print('\n data shape:', iris_data.data.shape)
print(iris_data['data'])

print("\n target type:", type(iris_data.target))
print("\n target shape:", iris_data.target.shape)
print(iris_data.target)



 feature_names type: <class 'list'>

 feature_names shape: 4
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

 target_names type: <class 'numpy.ndarray'>

 target_names shape: 3
['setosa' 'versicolor' 'virginica']

 data type: <class 'numpy.ndarray'>

 data shape: (150, 4)
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 

In [132]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score, cross_validate
from sklearn.datasets import load_iris

iris_data=load_iris()
dt_clf=DecisionTreeClassifier(random_state=156)

data=iris_data.data
label=iris_data.target

scores=cross_val_score(df_clf, data, label, scoring='accuracy', cv=3)
print('교차 검증별 정확도:',np.round(scores, 4))
print('평균 검증 정확도:',np.round(np.mean(scores),4))

교차 검증별 정확도: [0.98 0.92 0.98]
평균 검증 정확도: 0.96


In [133]:
grid_parameters={'max_depth':[1,2,3],
                'mon_samples_split':[2,3]}

In [138]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.datasets import load_iris

iris_data=load_iris()
X_train, X_test, y_train, y_test=train_test_split(iris_data.data, iris_data.target,
                                                 test_size=0.2, random_state=121)
dtree=DecisionTreeClassifier()

parameters={'max_depth':[1,2,3], 'min_samples_split':[2,3]}

In [139]:
grid_dtree=GridSearchCV(dtree, param_grid=parameters, cv=3, refit=True)

grid_dtree.fit(X_train, y_train)

score_df=pd.DataFrame(grid_dtree.cv_results_)
score_df[['params', 'mean_test_score', 'rank_test_score', 'split0_test_score','split1_test_score','split2_test_score']]

params  mean_test_score  rank_test_score  \
0  {'max_depth': 1, 'min_samples_split': 2}         0.700000                5   
1  {'max_depth': 1, 'min_samples_split': 3}         0.700000                5   
2  {'max_depth': 2, 'min_samples_split': 2}         0.958333                3   
3  {'max_depth': 2, 'min_samples_split': 3}         0.958333                3   
4  {'max_depth': 3, 'min_samples_split': 2}         0.975000                1   
5  {'max_depth': 3, 'min_samples_split': 3}         0.975000                1   

   split0_test_score  split1_test_score  split2_test_score  
0              0.700                0.7               0.70  
1              0.700                0.7               0.70  
2              0.925                1.0               0.95  
3              0.925                1.0               0.95  
4              0.975                1.0               0.95  
5              0.975                1.0               0.95

In [140]:
print('GridSearchCV 최적 파라미터:',grid_dtree.best_params_)
print('GridSearchCV 최고 정확도:{0:.4f}'.format(grid_dtree.best_score_))

GridSearchCV 최적 파라미터: {'max_depth': 3, 'min_samples_split': 2}
GridSearchCV 최고 정확도:0.9750


In [143]:
estimator=grid_dtree.best_estimator_

pred=estimator.predict(X_test)
print('테스트 데이터 세트 정확도:{0:.4f}'.format(accuracy_score(y_test, pred)))

테스트 데이터 세트 정확도:0.9667


In [144]:
from sklearn.preprocessing import LabelEncoder

items=['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']

encoder=LabelEncoder()
encoder.fit(items)
labels=encoder.transform(items)
print('인코딩 변환값:',labels)

인코딩 변환값: [0 1 4 5 3 3 2 2]


In [145]:
print('인코딩 클래스:',encoder.classes_)

인코딩 클래스: ['TV' '냉장고' '믹서' '선풍기' '전자레인지' '컴퓨터']


In [146]:
print('디코딩 원본값:',encoder.inverse_transform([4,5,2,0,1,1,3,3]))

디코딩 원본값: ['전자레인지' '컴퓨터' '믹서' 'TV' '냉장고' '냉장고' '선풍기' '선풍기']


In [148]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

items=['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']

encoder=LabelEncoder()
encoder.fit(items)
labels=encoder.transform(items)

labels=labels.reshape(-1,1)
print(labels)

oh_encoder=OneHotEncoder()
oh_encoder.fit(labels)
oh_labels=oh_encoder.transform(labels)
print('원-핫 인코딩 데이터')
print(oh_labels.toarray())
print('원-핫 인코딩 데이터 차원')
print(oh_labels.shape)

[[0]
 [1]
 [4]
 [5]
 [3]
 [3]
 [2]
 [2]]
원-핫 인코딩 데이터
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
원-핫 인코딩 데이터 차원
(8, 6)


In [149]:
import pandas as pd

df=pd.DataFrame({'items':['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']})

pd.get_dummies(df)

items_TV  items_냉장고  items_믹서  items_선풍기  items_전자레인지  items_컴퓨터
0         1          0         0          0            0          0
1         0          1         0          0            0          0
2         0          0         0          0            1          0
3         0          0         0          0            0          1
4         0          0         0          1            0          0
5         0          0         0          1            0          0
6         0          0         1          0            0          0
7         0          0         1          0            0          0

In [150]:
from sklearn.datasets import load_iris
import pandas as pd

iris=load_iris()
iris_data=iris.data
iris_df=pd.DataFrame(data=iris_data, columns=iris.feature_names)

print('feature 들 평균 값')
print(iris_df.mean())
print('\n feature 들 분산 값')
print(iris_df.var())

feature 들 평균 값
sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

 feature 들 분산 값
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


In [151]:
from sklearn.preprocessing import StandardScaler

scaler=StandardScaler()
scaler.fit(iris_df)
iris_scaled=scaler.transform(iris_df)

iris_df_scaled=pd.DataFrame(data=iris_scaled, columns=iris.feature_names)
print('feature 들 평균 값')
print(iris_df_scaled.mean())
print('\n feature 들 분산 값')
print(iris_df_scaled.var())

feature 들 평균 값
sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64

 feature 들 분산 값
sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64


In [152]:
from sklearn.preprocessing import MinMaxScaler

scaler=MinMaxScaler()
scaler.fit(iris_df)
iris_scaled=scaler.transform(iris_df)

iris_df_scaled=pd.DataFrame(data=iris_scaled, columns=iris.feature_names)
print('feature 들 최솟값')
print(iris_df_scaled.min())
print('\n feature 들 최대값')
print(iris_df_scaled.max())

feature 들 최솟값
sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64

 feature 들 최대값
sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64
